# Generated by Django 2.1.2 on 2018-11-03 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0004_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcart',
            name='cartItems',
        ),
        migrations.AddField(
            model_name='testcart',
            name='cartOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testcart',
            name='itemsInCart',
            field=models.ManyToManyField(to='cart.CartItem'),
        ),
    ]
