# Generated by Django 2.1.2 on 2018-11-03 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20181103_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.TestCart'),
        ),
        migrations.AlterField(
            model_name='testcart',
            name='cartOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testcart',
            name='status',
            field=models.CharField(blank=True, choices=[('b', 'Browsing'), ('p', 'Paid Order'), ('s', 'Shipped'), ('c', 'Cancelled')], default='t', help_text='Product availability', max_length=1),
        ),
    ]
