# Generated by Django 2.1.2 on 2018-10-09 21:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('manufacturer_name', models.CharField(max_length=100)),
                ('making_since', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['manufacturer_name', 'brand_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a product category(Example Video Cards)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the product', max_length=1000)),
                ('itemNumber', models.CharField(help_text='7 character item number ie 1237428 Olive garden dressing at costco', max_length=7, verbose_name='itemNumber')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Brand')),
                ('category', models.ManyToManyField(help_text='Select a category for this product', to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular product across whole system', primary_key=True, serialize=False)),
                ('productLine', models.CharField(max_length=200)),
                ('next_ship', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('t', 'test'), ('o', 'Sold Out'), ('a', 'Available'), ('b', 'Back Order')], default='t', help_text='Product availability', max_length=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
            ],
            options={
                'ordering': ['next_ship'],
            },
        ),
    ]
