# Generated by Django 2.1.2 on 2018-10-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=99, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
