# Generated by Django 2.1.2 on 2018-10-18 21:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular product across whole system', primary_key=True, serialize=False)),
                ('next_ship', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('b', 'Browsing'), ('o', 'ORDER'), ('a', 'a'), ('c', 'Cancelled')], default='t', help_text='Product availability', max_length=1)),
                ('category', models.ManyToManyField(help_text='Select a category for this product', to='products.Category')),
            ],
            options={
                'ordering': ['next_ship'],
            },
        ),
    ]
