# Generated by Django 2.1.2 on 2018-10-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='productList',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
