# Generated by Django 2.1.2 on 2018-10-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='cartOwner',
        ),
    ]
