# Generated by Django 2.1.2 on 2018-10-27 20:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20181027_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular product across whole system', primary_key=True, serialize=False),
        ),
    ]
