# Generated by Django 2.1.2 on 2018-10-30 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20181027_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartOwner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
