# Generated by Django 2.1.2 on 2018-11-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_paymentcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='cardNumber',
            field=models.CharField(help_text='Enter a fake card number', max_length=16, verbose_name='CardNumber'),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='cvv',
            field=models.CharField(help_text='max length = 4', max_length=4, verbose_name='cvv'),
        ),
    ]
