# Generated by Django 2.1.2 on 2018-11-04 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0015_paymentcard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='cardHolder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
