# Generated by Django 2.1.2 on 2018-11-04 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_wallette'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallette',
            old_name='walletteOwner',
            new_name='owner',
        ),
    ]
