# Generated by Django 2.1.2 on 2018-11-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20181104_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='exp',
            field=models.CharField(default='01 / 19', max_length=5, verbose_name='Expires'),
            preserve_default=False,
        ),
    ]
