# Generated by Django 2.1.2 on 2018-11-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_paymentcard_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='cardHolder',
            field=models.CharField(default='someGuy', help_text='Enter a CardHolder name', max_length=64, verbose_name='CardHolder'),
            preserve_default=False,
        ),
    ]
