# Generated by Django 2.1.2 on 2018-11-04 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0020_auto_20181104_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=True, choices=[('b', 'Browsing'), ('p', 'Paid Order'), ('s', 'Shipped'), ('c', 'Cancelled')], default='b', help_text='Product availability', max_length=1),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='add',
            field=models.ManyToManyField(to='products.Cart'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
