# Generated by Django 2.1.2 on 2018-11-04 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0021_auto_20181104_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular product across whole system', primary_key=True, serialize=False)),
                ('orders', models.ManyToManyField(to='products.Cart')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='add',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='owner',
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
