# Generated by Django 2.1.2 on 2018-11-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20181104_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shoppingSince',
            field=models.DateTimeField(default=None, verbose_name='date user grabbed this cart'),
            preserve_default=False,
        ),
    ]
