# Generated by Django 2.1.2 on 2018-11-08 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0023_cart_shoppingsince'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular product across whole system', primary_key=True, serialize=False)),
                ('address', models.CharField(help_text='Enter an address', max_length=25, verbose_name='Street name and Number')),
                ('city', models.CharField(help_text='max length = 25', max_length=25, verbose_name='City')),
                ('zip', models.CharField(max_length=15, verbose_name='Zip Code')),
                ('name', models.CharField(blank=True, help_text='Enter a name for this address such as Home, up to 32 characters!', max_length=32, null=True, verbose_name='Address Name: ')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
