# Generated by Django 2.1.2 on 2018-11-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(default='oh', help_text='Enter a state abbreviation', max_length=2, verbose_name='State'),
            preserve_default=False,
        ),
    ]
